### ISSUE TITLE
Geometry3D error

### ISSUE THREAD

**Issue by dpshepherd** [multiview-stitcher/multiview-stitcher#19]
Hi @m-albert,

Using the latest pypi build and also installing from Github, we are getting a Geometry3D failure for a 4D dataset (CZYX) with ~10% overlap. This data stitches fine in BigStitcher starting from the known stage coordinates. We are working with dask.array objects, but I also tried with np.ndarray and got the same error. Here is the code we use build to build the msims collection and then preview the positions,

We build each sim and the msim list from by looping over tiles, loading the `im_data` dask.array plus revelant metadata, and calling:
```python
sim = si_utils.get_sim_from_array(im_data,
                                dims=('c', 'z', 'y', 'x'),
                                scale=scale,
                                translation=tile_grid_positions,
                                transform_key='stage_metadata',
                                c_coords=channels)
msim = msi_utils.get_msim_from_sim(sim,scale_factors=[])
msims.append(msim)
```

followed by visualizing the positions,
```python
vis_utils.plot_positions(msims, transform_key='stage_metadata', use_positional_colors=False)
```
![image](https://github.com/multiview-stitcher/multiview-stitcher/assets/26783318/7a6e09eb-e987-4ea9-aa84-ff5759254a25)
which looks correct.

The register call is (doesn't matter what binning we try, always get an error)
```python
with dask.diagnostics.ProgressBar():
  params = registration.register(
      msims,
      reg_channel_index=0,
      transform_key='stage_metadata',
      new_transform_key='translation_registered',
      registration_binning={'z': 4, 'y': 2, 'x': 2},
      plot_summary=True,
  )
```

The traceback is 
```python
[                                        ] | 0% Completed | 2.01 s2024-04-05 18:58:27,779 [Geometry3D CRITICAL] V:8 E:12 F:7
[###################                     ] | 47% Completed | 2.21 s2024-04-05 18:58:27,999 [Geometry3D CRITICAL] V:8 E:12 F:7
[###############################         ] | 78% Completed | 2.41 s
Traceback (most recent call last):
  File "/home/qi2lab/Documents/github/wf-merfish/src/wf_merfish/run_postprocessing.py", line 197, in <module>
    run_wsi_stitching(Path('/media/qi2lab/BioProtean_WD/20240314_ECL_Cont0_2_F_PL025_01nM'))
  File "/home/qi2lab/Documents/github/wf-merfish/src/wf_merfish/postprocess/postprocess.py", line 579, in run_wsi_stitching
    params = registration.register(
  File "/home/qi2lab/miniconda3/envs/spots3d/lib/python3.10/site-packages/multiview_stitcher/registration.py", line 887, in register
    g = mv_graph.build_view_adjacency_graph_from_msims(
  File "/home/qi2lab/miniconda3/envs/spots3d/lib/python3.10/site-packages/multiview_stitcher/mv_graph.py", line 141, in build_view_adjacency_graph_from_msims
    overlap_results = compute(overlap_results, scheduler="processes")[0]
  File "/home/qi2lab/miniconda3/envs/spots3d/lib/python3.10/site-packages/dask/base.py", line 661, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/qi2lab/miniconda3/envs/spots3d/lib/python3.10/site-packages/multiview_stitcher/mv_graph.py", line 166, in get_overlap_between_pair_of_stack_props
    get_intersection_poly_from_pair_of_stack_props(
  File "/home/qi2lab/miniconda3/envs/spots3d/lib/python3.10/site-packages/multiview_stitcher/mv_graph.py", line 383, in get_intersection_poly_from_pair_of_stack_props
    return cphs[0].intersection(cphs[1])
  File "/home/qi2lab/miniconda3/envs/spots3d/lib/python3.10/site-packages/Geometry3D/geometry/body.py", line 14, in intersection
    return intersection(self, other)
  File "/home/qi2lab/miniconda3/envs/spots3d/lib/python3.10/site-packages/Geometry3D/calc/intersection.py", line 138, in intersection
    return inter_convexpolyhedron_convexpolyhedron(a,b)
  File "/home/qi2lab/miniconda3/envs/spots3d/lib/python3.10/site-packages/Geometry3D/calc/intersection.py", line 819, in inter_convexpolyhedron_convexpolyhedron
    return ConvexPolyhedron(tuple(cpg_set))
  File "/home/qi2lab/miniconda3/envs/spots3d/lib/python3.10/site-packages/Geometry3D/geometry/polyhedron.py", line 208, in __init__
    raise ValueError('Check for the number of vertices, faces and edges fails, the polyhedron may not be closed')
ValueError: Check for the number of vertices, faces and edges fails, the polyhedron may not be closed
```

Any thoughts on how we should move forward debugging this?

**Comment by m-albert** [comment]
Hi @dpshepherd, I tried to recreate your setup using the code below and couldn't reproduce.

The error should be independent of the image data. Could you post the image shapes and the values of `scale` and `tile_grid_positions`?

```python
import numpy as np
import dask.diagnostics

%matplotlib widget

from multiview_stitcher import registration, msi_utils, vis_utils
from multiview_stitcher import spatial_image_utils as si_utils

shape = [50, 500, 1000]
overlap = [0.1, 0.1, 0.1]

msims = []
for z_offset, y_offset, x_offset in zip(
    [0, 0, shape[0] * (1-overlap[0]), shape[0] * (1-overlap[0])],
    [0, 0, shape[1] * (1-overlap[1]), shape[1] * (1-overlap[1])],
    [0, shape[2] * (1-overlap[2]), 0, shape[2] * (1-overlap[2])],
    ):
    sim = si_utils.get_sim_from_array(
        np.ones([1,] + shape),
        dims=('c', 'z', 'y', 'x'),
        scale=None,
        translation={'z': z_offset, 'y': y_offset, 'x': x_offset},
        transform_key='stage_metadata',
        )
    msim = msi_utils.get_msim_from_sim(sim,scale_factors=[])
    msims.append(msim)

# vis_utils.plot_positions(msims,
#     transform_key='stage_metadata', use_positional_colors=True)

with dask.diagnostics.ProgressBar():
  params = registration.register(
      msims,
      reg_channel_index=0,
      transform_key='stage_metadata',
      new_transform_key='translation_registered',
      registration_binning={'z': 4, 'y': 2, 'x': 2},
      plot_summary=True,
  )
```

![Figure 2](https://github.com/multiview-stitcher/multiview-stitcher/assets/12528388/11fcdff2-ac5d-4f2e-8954-e527279c072f)

**Comment by dpshepherd** [comment]
I can't replicate this on a few other datasets, so I'm wondering if there is a unique failure mode at play here.

I'm going to close and will re-open if we run into it again.

Thanks!
