### ISSUE TITLE
Multiview-stitcher + Bioformats

### ISSUE THREAD

**Issue by Eddymorphling** [multiview-stitcher/multiview-stitcher#31]
Hi Folks, 
I am new to this and would like to try to test and see if this workflow would work for stitching + align + fusing a large multipoint Nikon .nd2 file. My datasets are multipoint acquisition, multi-channels, 3D stacks. Any advise on where to get started? From what I understand, the current workflow with `multiview-stitcher` can only read tiff files during IO operations and save as an OME-ZARR. Is it possible to also save as an HDF5/XML pair that can be viewed in BigStitcher in Fiji. 

I have been using BigStitcher + headless Fiji in the past sucks tasks but now BigStitcher has some issues reading these .nd2 files.

**Comment by m-albert** [comment]
Hi @Eddymorphling , thanks for writing here!

> Any advise on where to get started? From what I understand, the current workflow with multiview-stitcher can only read tiff files during IO operations and save as an OME-ZARR.

multiview-stitcher works with any data you're able to load into python. Ideally for large data this would be dask arrays. I don't have much experience with `nd2` myself, but would probably try these:
- https://github.com/tlambert03/nd2
```python
nd2.imread('some_file.nd2', dask=True)
```
- https://github.com/bioio-devs/bioio-nd2
```python
BioImage("my_file.nd2", reader=bioio_nd2.Reader).get_dask_array()
```

Once your data is in dask arrays, you'd indicate the pixel spacing and positions / initial transformations of your tiles as described e.g. [here](https://multiview-stitcher.github.io/multiview-stitcher/main/code_example/). This code example also shows how you could go on to register and fuse your data.

Please post any questions you have along the way!

**Comment by Eddymorphling** [comment]
Hi @m-albert 

Sorry I dropped the ball on this. I took a different approach to stitch these .nd2 files in the end that turned out to be successful. 

I have a follow-question regarding `multiview-stitcher.` I had some time recently to written a python script that I adapted from one of your notebooks to stitch, align, register and fuse Lightsheet datasets acquired with a Blaze LS system. THese datasets are quiet large so I included `dask `to lazy load datasets and create 3D OME-NGFF Zarr arrays. But here is where I am stuck - the stitching does not work out well, the scripts reads the X-Y tile positions from the file names automatically but aligns them in a un-directional (left-right-left-right) array but the datasets were acquired left-right-left-right. I also tried to Visualize tile positions/configuration before it does any registeration or alignment but that gives me an `IndexError: list index out of range` error. Not sure how to go about this.

Would you have any suggestions on how to troubleshoot this? Happy to share what I wrote in Python if that helps. Let me know Thanks.

**Comment by m-albert** [comment]
Hi @Eddymorphling, that sounds like a solvable problem. Happy to have a look at the python script if you post it!

**Comment by Eddymorphling** [comment]
Thank you, appreciate the help. Actually the error is at the channel/registration I believe. 

Here is my script. The error is message follows the script. This scripts currently created a 3D-NGFF-zarr array for all my tiles but fails at the channel alignment/registration step. The code reads channel, tile info and z-slice info from the `ome.tif` filenames in the input folder.


```
import os
import re
import xarray as xr
from pathlib import Path
import dask.array as da
from dask import delayed
from dask.diagnostics import ProgressBar
import ngff_zarr
import numpy as np
import tifffile
from multiview_stitcher import (
    fusion,
    io,
    msi_utils,
    ngff_utils,
    registration,
)
from tqdm import tqdm


def read_image(image_path):
    return tifffile.imread(image_path)

def main():
    base_dir = "/Raw_Data/240814_20240814_IMG"

    # Define a suffix for unique file naming
    suffix = "Dataset"

    def get_prefix_with_blaze(directory):
        filenames = [f.name for f in Path(directory).glob('**/*.tif')]
        if not filenames:
            raise ValueError("No TIFF files found in the directory.")
        for name in filenames:
            if "Blaze" in name:
                prefix = name.split("Blaze")[0] + "Blaze"
                return prefix
        raise ValueError("No filenames with 'Blaze' found.")

    def extract_ranges(directory, prefix):
        tile_x_set, tile_y_set, channel_set, z_slice_set = set(), set(), set(), set()
        pattern = re.compile(rf'{re.escape(prefix)}\[(\d+) x (\d+)\]_C(\d+)_xyz-Table Z(\d+)\.ome\.tif')

        for filename in Path(directory).glob('**/*.tif'):
            match = pattern.match(filename.name)
            if match:
                tile_x, tile_y, channel, z_slice = map(int, match.groups())
                tile_x_set.add(tile_x)
                tile_y_set.add(tile_y)
                channel_set.add(channel)
                z_slice_set.add(z_slice)

        return (sorted(tile_x_set), sorted(tile_y_set), 
                sorted(channel_set), sorted(z_slice_set))

    common_prefix = get_prefix_with_blaze(base_dir)

    # Automatically determine ranges from filenames
    tile_x_range, tile_y_range, channels, z_slices = extract_ranges(base_dir, common_prefix)

    def get_filename_from_tile_channel_z(prefix, tile_x, tile_y, channel, z_slice):
        return f'{prefix}[{tile_x:02d} x {tile_y:02d}]_C{channel:02d}_xyz-Table Z{z_slice:04d}.ome.tif'

    tile_x, tile_y, channel, z_slice = 0, 0, 0, 1
    print('Example filename:\n', get_filename_from_tile_channel_z(common_prefix, tile_x, tile_y, channel, z_slice))

    # Pixel scaling info for raw images
    scale = {'z': 3, 'y': 0.22, 'x': 0.22}
    overlap = 0.2
    overwrite = True
    msims = []

    for tile_x in tqdm(tile_x_range, desc="Processing tiles"):
        for tile_y in tile_y_range:
            zarr_path = os.path.join(base_dir, f'tile_{tile_x:02d}_{tile_y:02d}_{suffix}')

            if not os.path.exists(zarr_path) or overwrite:
                tile_grid_position = {'z': 0, 'y': tile_y, 'x': tile_x}

                # Collect images for each channel and z-slice
                im_data_list = []
                for ch in channels:
                    channel_images = []
                    for z in z_slices:
                        # Skip Z0000
                        if z == 0:
                            continue

                        image_path = os.path.join(base_dir, get_filename_from_tile_channel_z(common_prefix, tile_x, tile_y, ch, z))
                        
                        # Verify the file exists
                        if not os.path.exists(image_path):
                            print(f"File not found: {image_path}")
                            continue
                        
                        # Read the image using Dask delayed
                        image = delayed(read_image)(image_path)
                        channel_images.append(image)

                    # Compute the images in parallel
                    channel_images = da.compute(*channel_images)

                    # Ensure all images have the same shape
                    shapes = [img.shape for img in channel_images]
                    if len(set(shapes)) > 1:
                        print(f"Inconsistent image shapes found: {shapes}")
                        continue

                    # Stack 2D slices into a 3D array for this channel
                    channel_stack = np.stack(channel_images, axis=0)
                    im_data_list.append(channel_stack)

                # Convert list to a numpy array
                im_data = np.stack(im_data_list, axis=0)

                # Ensure the shape matches expected 3D (c, z, y, x)
                shape = {dim: im_data.shape[-idim] for idim, dim in enumerate(scale.keys())}
                translation = {dim: tile_grid_position[dim] * (1 - overlap) * shape[dim] * scale[dim]
                               for dim in scale}

                ngff_im = ngff_zarr.NgffImage(
                    im_data,
                    dims=('c', 'z', 'y', 'x'),
                    scale=scale,
                    translation=translation,
                )

                ngff_multiscales = ngff_zarr.to_multiscales(ngff_im)

                ngff_zarr.to_ngff_zarr(zarr_path, ngff_multiscales)

                msim = ngff_utils.ngff_multiscales_to_msim(
                    ngff_zarr.from_ngff_zarr(zarr_path),
                    transform_key=io.METADATA_TRANSFORM_KEY)

                msims.append(msim)

    # Check if msims is empty
    if not msims:
        print("No images loaded into msims.")
        return

    print(f'Number of msims: {len(msims)}')

       # Channel alignment and registration
    perform_channel_alignment = True
    channel_alignment_tile_index = 0

    curr_transform_key = 'affine_metadata'
    if perform_channel_alignment:
        curr_transform_key = 'affine_metadata_ch_reg'

        channels = msims[channel_alignment_tile_index]['scale0/image'].coords['c']
        if len(channels) == 0:
            print("No channels found for channel alignment.")
            return

        msims_ch_reg = [msi_utils.multiscale_sel_coords(msims[channel_alignment_tile_index], {'c': ch})
                        for ch in channels]

        with ProgressBar():
            params_c = registration.register(
                msims_ch_reg,
                registration_binning={'z': 2, 'y': 2, 'x': 2},
                reg_channel_index=0,
                transform_key='affine_metadata',
                pre_registration_pruning_method=None,
            )

        params_c = xr.concat(params_c, dim='c').assign_coords({'c': channels})

        for msim in msims:
            msi_utils.set_affine_transform(
                msim, params_c, transform_key=curr_transform_key, base_transform_key='affine_metadata')
    
    # Registration and stitching
    with ProgressBar():
        try:
            params = registration.register(
                msims,
                registration_binning={'z': 2, 'y': 2, 'x': 2},
                reg_channel_index=0,
                transform_key=curr_transform_key,
                new_transform_key='affine_registered',
            )
        except IndexError as e:
            print(f"Error during registration: {e}")
            return

    for imsim, msim in enumerate(msims):
        affine = np.array(msi_utils.get_transform_from_msim(msim, transform_key='affine_registered')[0])
        print(f'_tile_index {imsim}\n', affine)

    output_dir = base_dir
    output_filename = os.path.join(output_dir, f'fused_{suffix}.zarr')

    fused = fusion.fuse(
        [msi_utils.get_sim_from_msim(msim) for msim in msims],
        transform_key='affine_registered',
        output_chunksize=256,
    )

    print(f'Fusing views and saving output to {output_filename}...')
    with ProgressBar():
        fused_ngff = ngff_utils.sim_to_ngff_image(
            fused,
            transform_key='affine_registered')

        # Create multiscale representation with specified scale factors
        fused_ngff_multiscales = ngff_zarr.to_multiscales(fused_ngff, scale_factors=[2,4,6])

        ngff_zarr.to_ngff_zarr(
            output_filename,
            fused_ngff_multiscales,
        )

    mfused = ngff_utils.ngff_multiscales_to_msim(
        ngff_zarr.from_ngff_zarr(output_filename),
        transform_key='affine_registered')

    downsampled_data = fused[::2, ::2, ::2]  # Downsample by factor of 2 in each dimension
    downsampled_tiff_filename = os.path.join(output_dir, f'Fused_downsampled_{suffix}.tif')

    print(f'Saving downsampled TIFF to {downsampled_tiff_filename}...')
    tifffile.imwrite(downsampled_tiff_filename, downsampled_data)  

if __name__ == '__main__':
    main()
```



**Error logs:**

```

Processing tiles:   0%|          | 0/3 [00:00<?, ?it/s]
Processing tiles:  33%|███▎      | 1/3 [46:58<1:33:56, 2818.17s/it]
Processing tiles:  67%|██████▋   | 2/3 [1:35:43<48:01, 2881.00s/it]
Processing tiles: 100%|██████████| 3/3 [2:21:47<00:00, 2827.91s/it]
Processing tiles: 100%|██████████| 3/3 [2:21:47<00:00, 2835.96s/it]
Traceback (most recent call last):
  File "/home/HPC_Jobs/napari-stitcher_Blaze.py", line 242, in <module>
    main()
  File "/home/HPC_Jobs/napari-stitcher_Blaze.py", line 176, in main
    params_c = registration.register(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/envs/napari-stitcher/lib/python3.11/site-packages/multiview_stitcher/registration.py", line 1552, in register
    reg_channel = sims[0].coords["c"][reg_channel_index]
                  ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/conda/envs/napari-stitcher/lib/python3.11/site-packages/xarray/core/dataarray.py", line 891, in __getitem__
    return self.isel(indexers=self._item_key_to_dict(key))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/envs/napari-stitcher/lib/python3.11/site-packages/xarray/core/dataarray.py", line 872, in _item_key_to_dict
    key = indexing.expanded_indexer(key, self.ndim)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/envs/napari-stitcher/lib/python3.11/site-packages/xarray/core/indexing.py", line 235, in expanded_indexer
    raise IndexError("too many indices")
IndexError: too many indices

```
